### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by anyasinyavskaya** [ShiiRochi/wavesurfer-react#51]
Hi
I'm trying to build my project in which wavesurfer-react 2.1.6 version is imported:

`import {WaveSurfer, WaveForm} from 'wavesurfer-react';
`

and I'm getting an error
```
ReferenceError: self is not defined
    at Object.<anonymous> (/path-to-project/node_modules/wavesurfer.js/dist/webpack:/WaveSurfer/webpack/universalModuleDefinition:10:2)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._compile (/path-to-project/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.newLoader [as .js] (/path-to-project/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/path-to-project/node_modules/wavesurfer-react/dist/utils/createWavesurfer.js:1:1)
```
Do you have any suggestions, is this a problem with my build or somewhere inside the package? I would be glad of any help

**Comment by ShiiRochi** [comment]
@anyasinyavskaya, hello! 
1. What version of **wavesurfer.js** you're using?
2. Please, see [wavesurfer.js#2359](https://github.com/katspaugh/wavesurfer.js/issues/2359), maybe in original package you will get an answer

Some precautions: 
1. if you're using Next, try to surround `wavesurfer-react` components with dynamic call with `ssr` set to `false`;
2. if you're using other SSR stuff, try to surround `wavesurfer-react` components with client-only parent components that will render components only in browser environment.

**Comment by bramses** [comment]
Running into the same issue (in NextJS)

```
import dynamic from "next/dynamic";
const WaveSurfer = dynamic(() => import("wavesurfer-react"), {
  ssr: false,
});
```

**Comment by ShiiRochi** [comment]
@bramses, hi, I tried to reproduce it and succeeded.

I will place working code below, but it should be mentioned that it a little bit tricky.
 
```jsx
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import dynamic from "next/dynamic";
import styles from '../styles/Home.module.css'
import {useCallback, useEffect, useState} from "react";

const WaveSurfer = dynamic(() => import("wavesurfer-react").then(m => m.WaveSurfer), { ssr: false });

const Home: NextPage = () => {
  const [plugins, setPlugins] = useState([]);

  const onMount = useCallback((ws$) => {
    console.log({ ws$ });
    if (!ws$) return;
    ws$.load("/record_1.mp3");
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") return;
    /*
     dynamic("...") with wavesurfer plugins doesn't work
     because next will surround it with LoadableComponent
    */
    import("wavesurfer.js/dist/plugin/wavesurfer.timeline").then((TimelinePlugin) => {
      setPlugins([{
        plugin: TimelinePlugin.default,
        options: {
          container: "#timeline"
        }
      }]);
    });
  }, [])

  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div style={{ width: "100%" }}>
          {/*
          We cannot you dynamic with WaveForm as far as dynamic surrounds component with LoadableComponent,
          that makes it impossible to read container from WaveForm's props.
          */}
          <WaveSurfer onMount={onMount} container="#wavesurfer" plugins={plugins}>
            <div id="wavesurfer"/>
            <div id="timeline" />
          </WaveSurfer>
        </div>
      </main>
    </div>
  )
}

export default Home
```

**Comment by bramses** [comment]
@ShiiRochi awesome, ty for this! will try this method when i get home and edit this message with results :)
